### PR TITLE
fix(data models): fix issue causing derived statistics not to be updated when a bonus is applied

### LINKED ISSUE #217: Mod Changes to Attributres do not scale Movement Rate and Sense Range properly
**Describe the bug**  
One random thing I noticed when I did a modifier for AWA is that it did not change the actors sense range same with a move range with spd mod. which should dynamically change with modifiers.
The only things that SHOULDNT change with Attribute mods changing their base is Defenses (this seems to work correctly), max hp/focus(also good), and max invest (auto calc not in system yet so doesnt work). Honestly just seems like the default assumption is that mods only affect the skills going up which isnt true and should be adjusted.

**To Reproduce**  
_Steps to reproduce the behavior:_
1.create a item to add a mod to AWA or SPD stat 

Image

2. Make sure that the modifer would jump the Attribute up to the next tier of movement or sense range.
3. see that it does not work with sense or movement but that revelant skills related to the attribute do.

**Expected behavior**  
Sense or Movement range go up, as do all relevant skill modifiers. does not increase related defence, or max hp/focus/invest

**Foundry VTT Version**  
12.221

**Cosmere RPG System Version**  
0.2.2

**Browser**  
Chrome

**Checklist:**
- [x] I have searched the existing issues to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by stanavdb**
*Type**  
What type of pull request is this? (e.g., Bug fix, Feature, Refactor, etc.)

- [x] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Other (please describe):

**Description**
This PR makes it so the attribute bonus is correctly applied to derived statistics (e.g. movement rate)

**Related Issue**  
Closes #217 

**How Has This Been Tested?**  
1. Add effect that modifies an attribute bonus (`system.attributes.spd.bonus` to +2)
2. Toggle effect on
3. See movement rate increase

**Checklist:**  
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes do not introduce any new warnings or errors.
- [x] My PR does not contain any copyrighted works that I do not have permission to use.
- [x] I have tested my changes on Foundry VTT version: 12.331

### CODE REVIEW

File: src/system/data/actor/common.ts [hunk 1]
```diff
@@ -56,6 +56,11 @@ interface CurrencyDenominationData {
     convertedValue: Derived<number>;
 }
 
+interface AttributeData {
```
Comment (zithith) [inline src/system/data/actor/common.ts:59]: This could probably be moved up to somewhere more universal. I know there are a couple of places in the roll calculations for items where I have in-lined this type definition

**Review by zithith — APPROVED** [review]

**Review by MangoFVTT — APPROVED** [review]

File: src/system/data/actor/common.ts (hunk 1 above)
Comment (stanavdb) [reply src/system/data/actor/common.ts]: I could only find one other place this type was defined (see latest commit). Let me know if you have any I missed

Comment (zithith) [reply src/system/data/actor/common.ts]: I think that's it. I got a little mixed up between where I had basically defined the same type, but it's inferred as inline variables (see https://github.com/the-metalworks/cosmere-rpg/blob/075d82493e7c3b0ad3be4e47ebccfe7599bf5479/src/system/documents/item.ts#L1216 and the skill test function above it). So this probably won't help in those instances, but it's helpful to have available in case someone needs to refactor that. There's also something similar with the Skill object up on line 391 of that file too.

**Review by zithith — APPROVED** [review]
