### PR TITLE
Fix for 157 - Unarmed graze damage

### LINKED ISSUE #157: Unarmed Stike Fails to Roll
**Describe the bug**  
UnarmStrike Fails to roll or output to chat.

**To Reproduce**  
_Steps to reproduce the behavior:_
1. _Go to character sheet with an unarmed attack weapon
2. _Click on the roll for the unarmed attack
3. _See that it does not output

**Expected behavior**  
Unarmed attack should roll (even if it just uses flat damage and not the scaling damage)

**Screenshots**  
image

**Foundry VTT Version**  
12.331

**Cosmere RPG System Version**  
0.2.0

**Browser**  
Chrome

**Additional context**  
Tried with a new PC and a already created on from the last update. Same issue

**Checklist:**
- [x] I have searched the existing issues to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by zithith**
**Type**  
- [x] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Other (please describe):

**Description**  
Updated the graze formula fall back for when the base damage formula doesn't include dice.

**Related Issue**  
Closes #157 

**How Has This Been Tested?**  
Locally rolling unarmed attacks and standard attacks

**Screenshots (if applicable)**  
_Add screenshots or GIFs that help illustrate the changes, especially if they affect the UI or user-facing aspects of the system._

**Checklist:**  
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes do not introduce any new warnings or errors.
- [ ] My PR does not contain any copyrighted works that I do not have permission to use.
- [ ] I have tested my changes on Foundry VTT version: [insert version here].

**Additional context**  
_Add any other context or information here that would be useful for reviewers._

### CODE REVIEW

**Comment by zithith** [comment]
This isn't a full fix, see code comments

File: src/system/documents/chat-message.ts [hunk 1]
```diff
@@ -261,8 +261,7 @@ export class CosmereChatMessage extends ChatMessage {
             const tooltipNormal = $(await rollNormal.getTooltip());
             this.enrichDamageTooltip(rollNormal, type, tooltipNormal);
             tooltipNormalHTML +=
-                tooltipNormal.find('.tooltip-part')[0].outerHTML;
-
+                tooltipNormal.find('.tooltip-part')[0]?.outerHTML || ``;
```
Comment (zithith) [inline src/system/documents/chat-message.ts:264]: this empty string alternative is a clutch.
It works, but the tooltips are no longer consistent. Screenshot:
image

Comment (MangoFVTT) [reply src/system/documents/chat-message.ts:264]: Hmm this is annoying yeah. The problem is that the core foundry code only generates tooltips for dice. To show constants I do enrichment AFTER the tooltip is generated but that requires an already existing tooltip which obviously doesn't exist here. Not sure what the best fix would be unfortunately, i'd have to have a proper think about even more complicated tooltip generation code. I'll take a look at what the dnd5e system does in this case to get ideas

File: src/system/documents/item.ts [hunk 2]
```diff
@@ -518,9 +518,14 @@ export class CosmereItem<
         );
 
         // Make the graze pool and roll it
+        const defaultGraze = roll.terms.every(
+            (term) => !(term instanceof foundry.dice.terms.DiceTerm),
+        )
```
Comment (MangoFVTT) [inline src/system/documents/item.ts:523]: Minor nitpick: it's faster to do `!roll.terms.some(term => foundry.dice.terms.DiceTerm)` because that will exit out early if a single DiceTerm is found, whereas every will always run the full iteration

**Comment by stanavdb** [comment]
My commit fixes the tooltip issue. Did however run into a different (not quite related) bug; If a damage roll has multiple different dice, the tooltip doesn't render those correctly, it just drops anything beyond the first die type. 
image
image

**Comment by MangoFVTT** [comment]
> Did however run into a different (not quite related) bug; If a damage roll has multiple different dice, the tooltip doesn't render those correctly, it just drops anything beyond the first die type.

Interesting 🤔 the dice tooltip is generated by foundry itself and injected into a handlebars template, so it may be an error in the template that's causing the issue. I'll have to check when I have time

The rest looks good to me

**Comment by zithith** [comment]
Great work Stan! Good solutions, I like everything here.
The multi dice thing can be raised as a separate issue?

**Review by stanavdb — APPROVED** [review]
